export const REWARD_THRESHOLDS = {
    SEARCHES_FOR_HIDDEN_DEALS: 3,
    FILTERS_FOR_VISA_SCORE: 5,
    STREAK_FOR_PRIORITY: 7,
};

export const REWARD_TYPES = {
    HIDDEN_DEALS: 'HIDDEN_DEALS',
    VISA_SUCCESS_SCORE: 'VISA_SUCCESS_SCORE',
    EMBASSSY_SPEED_RANK: 'EMBASSY_SPEED_RANK',
    INSTANT_APPROVAL: 'INSTANT_APPROVAL',
};
